tagada

diff --git a/lib/lib-visp_install b/lib/lib-visp_install
--- a/lib/lib-visp_install
+++ b/lib/lib-visp_install
@@ -73,7 +73,7 @@ function configureNetwork() {
         echo "IP Address for administration network (brO)"
         read -p "Ex: 192.168.1.1/24 : " ipbr0
 
-        ipbr0=`echo $ipbr0 | awk -F \/ {'print$1'}`
+        export ipbr0=`echo $ipbr0 | awk -F \/ {'print$1'}`
         maskbr0=`ipcalc $ipbr0 | grep Netmask | awk {'print$2'}`
         netbr0=`ipcalc $ipbr0 | grep Network | awk {'print$2'} | awk -F / {'print$1'}`
 
@@ -129,9 +129,36 @@ function configureNatForward() {
 
         # create exitLine to known the line number of "exit 0" 
 	cp ./scripts/firewall.sh /usr/sbin/firewall.sh
+	chmod u+x /usr/sbin/firewall.sh
 	ip=`ip addr show dev br0 | grep global | awk {'print$2'} | cut -d'/' -f-1`
 	echo "/usr/sbin/firewall.sh" > /etc/rc.local
 	echo "exit 0" >> /etc/rc.local
+}
+
+function installCgroup() {
+
+        cgroupFstab=`grep cgroup /etc/fstab`
+
+        if [ -z "$cgroupFstab" ]
+        then
+                cat << EOF >> /etc/fstab
+
+cgroup          /sys/fs/cgroup  cgroup  defaults        0       0
+
+EOF
+                cgroupMount=`mount | grep cgroup`
+                if [ -z $cgroupMount ]
+                then
+                        mount cgroup
+
+                        if [ $? -ne 0 ]
+                        then
+                                echo "Cannot mount cgroup"
+                                exit 1
+                        fi
+                fi
+        fi
+
 }
 
 
